In [2]:
import pandas as pd
import numpy as np

In [ ]:
professions = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/Prestige.csv', index_col="name")
professionsOriginal = professions.copy()
dc = {'income': 'IncomeDollarsPerYear'}
professionsOriginal.rename(columns= dc, inplace=True)
professionsOriginal.rename(columns={'women':'womenPercent', 'prestige' : 'prestigeIndicaton'},inplace=True)
professionsOriginal.rename(index={'accountants':'bookkeepers', 'general.managers':'managers'},inplace=True)
professionsOriginal.head()

womensFiltr = professions.women > 10
womensFiltr.head()


z = professions[womensFiltr]
a = z.duplicated(subset="type",keep="first")
b = z[~a].fillna("unknown")
b

professions.loc[womensFiltr,"women"] += 135001
professions

professions.loc["accountants","women"]

NameError: name 'pd' is not defined

:

In [178]:
professions = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/Prestige.csv', index_col="name")
professions.head(5)
professions.loc["chemists","type"] = "scientist"
professions.head()

isScientist = professions.type == "scientist"
licznik = 0
#test po pythonowemu
for i in range(len(isScientist)) :
   if isScientist.iloc[i] == False:
       licznik = licznik + 1
z

isScientist.value_counts()
hh = professions[isScientist]
professions.loc[isScientist,"prestige"] = 90
professions.head()
professions["income"] = professions["income"].astype(float)

professions.loc[isScientist,"income"] = professions["income"] * 1.5
professions.head()

professions.loc[isScientist,"income"] *= 1.5
professions.head(5)

                     education    income  women  prestige  census       type
name
gov.administrators       13.11  12351.00  11.16      68.8    1113       prof
general.managers         12.26  25879.00   4.02      69.1    1130       prof
accountants              12.77   9271.00  15.70      63.4    1171       prof
purchasing.officers      11.42   8865.00   9.11      56.8    1175       prof
chemists                 14.62  18906.75  11.68      90.0    2111  scientist

In [212]:
professions = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/Prestige.csv')

dict = {
    "name" : "data scientist",
    "education" : np.nan,
    "income" : np.nan,
    "women" : np.nan,
    "prestige" : np.nan,
    "census" : np.nan,
    "type" : np.nan,
}

professions = pd.concat([professions, pd.DataFrame([dict])], ignore_index=True)
professions.tail()

taxi = professions.loc[professions.name  == "taxi.drivers"]

professions.drop(98)

professions = pd.concat([professions, taxi], ignore_index=True)
professions.tail(5)

del professions["census"]
professions.drop(columns = "type", inplace=True)
professions

                    name  education   income  women  prestige
0     gov.administrators      13.11  12351.0  11.16      68.8
1       general.managers      12.26  25879.0   4.02      69.1
2            accountants      12.77   9271.0  15.70      63.4
3    purchasing.officers      11.42   8865.0   9.11      56.8
4               chemists      14.62   8403.0  11.68      73.5
..                   ...        ...      ...    ...       ...
99          longshoremen       8.37   4753.0   0.00      26.1
100          typesetters      10.00   6462.0  13.58      42.2
101          bookbinders       8.55   3617.0  70.87      35.2
102       data scientist        NaN      NaN    NaN       NaN
103         taxi.drivers       7.93   4224.0   3.59      25.1

[104 rows x 5 columns]

In [47]:
fortune = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/Fortune_500_2017.csv')
fortune[100:105][["Title","Employees"]]
fortune.set_index("Title", inplace=True)
fortune.sort_index(inplace=True)
fortune["A":"a"]

,Rank,Website,Employees,Sector,Industry,Hqlocation,Hqaddr,Hqcity,Hqstate,Hqzip,...,Ceo-title,Address,Ticker,Fullname,Revenues,Revchange,Profits,Prftchange,Assets,Totshequity
Title,,,,,,,,,,,,,,,,,,,,,
A-Mark Precious Metals,395,http://www.amark.com,83,Materials,Miscellaneous,"Santa Monica, CA",429 Santa Monica Blvd.,Santa Monica,CA,90401,...,Chief Executive Officer & Director,"429 Santa Monica Blvd., Santa Monica, CA 90401",AMRK,"A-Mark Precious Metals, Inc.",6784,11.8,9.3,31.5,437,63.0
ABM Industries,500,http://www.abm.com,110000,Business Services,Diversified Outsourcing Services,"New York, NY",1 Liberty Plaza,New York,NY,10006,...,"President, Chief Executive Officer & Director","1 Liberty Plaza, New York, NY 10006",ABM,ABM Industries Incorporated,5145,-2.8,57.2,-25,2281,974.0
ADP,240,http://www.adp.com,57000,Business Services,Diversified Outsourcing Services,"Roseland, NJ",1 ADP Blvd.,Roseland,NJ,7068,...,"President, Chief Executive Officer & Director","1 ADP Blvd., Roseland, NJ 07068",ADP,"Automatic Data Processing, Inc.",11668,1.7,1492.5,2.8,43670,4482.0
AECOM,161,http://www.aecom.com,87000,Engineering & Construction,"Engineering, Construction","Los Angeles, CA",1999 Ave. of the Stars,Los Angeles,CA,90067,...,Chairman & Chief Executive Officer,"1999 Ave. of the Stars, Los Angeles, CA 90067",ACM,AECOM,17411,-3.2,96.1,-28.7,13727,3367.0
AES,194,http://www.aes.com,19000,Energy,Utilities: Gas and Electric,"Arlington, VA",4300 Wilson Blvd.,Arlington,VA,22203,...,"President, Chief Executive Officer & Director","4300 Wilson Blvd., Arlington, VA 22203",AES,The AES Corporation,14287,-4.5,-1130.0,-469.3,36119,2794.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Xerox,162,http://www.xerox.com,133600,Technology,Computer Peripherals,"Norwalk, CT",45 Glover Ave.,Norwalk,CT,6850,...,Chief Executive Officer & Director,"45 Glover Ave., Norwalk, CT 06850",XRX,Xerox Corporation,17126,-8.2,-477.0,-200.6,18145,4803.0
Yahoo,498,http://www.yahoo.com,8500,Technology,Internet Services and Retailing,"Sunnyvale, CA",701 First Ave.,Sunnyvale,CA,94089,...,"President, Chief Executive Officer & Director","701 First Ave., Sunnyvale, CA 94089",YHOO,Yahoo! Inc.,5169,4.0,-214.3,5.2,48083,31049.0
Yum Brands,422,http://www.yum.com,90000,"Hotels, Restaurants & Leisure",Food Services,"Louisville, KY",1441 Gardiner Lane,Louisville,KY,40213,...,Chief Executive Officer & Director,"1441 Gardiner Lane, Louisville, KY 40213",YUM,"Yum! Brands, Inc.",6366,-51.4,1619.0,25.2,5478,-5656.0
Yum China Holdings,399,http://ir.yumchina.com,420000,"Hotels, Restaurants & Leisure",Food Services,"Plano, TX",7100 Corporate Dr.,Plano,TX,75024,...,Chief Executive Officer & Director,"7100 Corporate Dr., Plano, TX 75024",YUMC,"Yum China Holdings, Inc.",6752,4.0,502.0,-13.4,3727,2377.0
Zimmer Biomet Holdings,352,http://www.zimmerbiomet.com,18500,Health Care,Medical Products and Equipment,"Warsaw, IN",345 E. Main St.,Warsaw,IN,46580,...,"President, Chief Executive Officer & Director","345 E. Main St., Warsaw, IN 46580",ZBH,"Zimmer Biomet Holdings, Inc.",7684,28.1,305.9,108.1,26684,9669.0

In [185]:
fortune = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/Fortune_500_2017.csv', usecols=["Rank","Title","Industry","Hqlocation","Sector"])

fortune["Sector"] = fortune["Sector"].str.upper()
fortune

fortune["Industry"].str.lower().str.contains("comp")

fortune = fortune.rename(columns = {"Hqlocation" : "HQLOCATION"})  # ZMIANA NA PRZYPOMNIENIE

fortune.loc[35,"HQLOCATION"] = "cinicii, OHIO, BORUTA"

expanded = fortune["HQLOCATION"].str.strip().str.split(", ", expand=True, n=0)
fortune[["City", "State", "test"]] = expanded

fortune.drop(columns="HQLOCATION", inplace=True)
#fortune["test"] = fortune["test"].fillna("?")
#fortune[fortune["test"] != "?"]

frame = fortune.copy()

def BuildShortcut(row):
    industry = row["Industry"]
    result = ""
    for i in industry.split(" "):
        result += i[0]
    return result

fortune["shortcut"] = fortune.apply(BuildShortcut, axis = 1)
fortune

def BuildTitleLenght(row):
    title = row["Title"]
    space = -1
    for i in title.split():
        space += 1

    text = f'ilość słow, {len(title.split())}, ilosc spacji: {space}'
    return text

fortune["Title Info"] = fortune.apply(BuildTitleLenght, axis=1)
fortune

def laczenie(column):
    column = column.fillna("").astype(str)
    jeden_dlugi = " ".join(column)
    return jeden_dlugi

wiersz =  fortune.apply(laczenie, axis= 0)
fortune = pd.concat([fortune, pd.DataFrame([wiersz])], ignore_index=True)
fortune.tail(3)

pd.DataFrame([wiersz])

type([wiersz])

list

In [229]:
fb = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/mrbean_facebook_statuses_with_nulls.csv', usecols=["status_message","status_type","link_name","num_reactions","num_shares","num_likes" ]) # 14.9KB start
#fb.info(memory_usage="deep")
newNames = {"status_message" : "MessageStatus", 
            "link_name" : "Link",
            "status_type" : "Type",
            "num_reactions" : "ReactionsCount",
            "num_shares" : "SharesCount",
            "num_likes" : "LikesCount"}

fb.rename(newNames, axis=1, inplace=True)
fb["MessageStatus"] = fb["MessageStatus"].fillna("Empty")
fb["Type"] = fb["Type"].astype("category")
fb["Link"] = fb["Link"].astype("category")

fb["ReactionsCount"] = fb["ReactionsCount"].fillna(0).astype("int32")
fb["SharesCount"] = fb["SharesCount"].astype("int32")
fb["LikesCount"] = fb["LikesCount"].astype("int32")
fb.info(memory_usage="deep")
fb

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MessageStatus   56 non-null     str
 1   Link            56 non-null     category
 2   Type            56 non-null     category
 3   ReactionsCount  56 non-null     int32
 4   SharesCount     56 non-null     int32
 5   LikesCount      56 non-null     int32
dtypes: category(2), int32(3), str(1)
memory usage: 10.4 KB

,MessageStatus,Link,Type,ReactionsCount,SharesCount,LikesCount
0,It's time for Mr Bean and Teddy to get ready f...,Mr Bean - Preparing To Go Camping,video,16570,338,16079
1,Empty,Timeline Photos,photo,119886,1657,114008
2,Empty,Timeline Photos,photo,0,10050,218579
3,Mr Bean is ready to do some shopping but bewar...,www.youtube.com,video,20913,257,20338
4,Empty,Timeline Photos,photo,223602,2228,215591
5,Mr. Bean's sweet treat causes him pain!,Mr Bean - Broken Tooth,video,24742,448,23977
6,Mr Bean's chasing a ray of sunshine!\r\nhttps:...,Mr Bean - Ray Of Sunshine,video,21886,471,21246
7,Mr Bean is enjoying the sunshine....that is un...,Mr Bean - Sun Block,video,22015,546,21293
8,Empty,Timeline Photos,photo,196913,9849,190476
9,Empty,Timeline Photos,photo,196366,5378,190857
10,Mr Bean competes with a Royal Guard. Can he b...,www.youtube.com,video,30109,905,28906
11,Empty,Timeline Photos,photo,233121,3423,218235
12,HAPPY GEEK PRIDE DAY! Watch Mr Bean's geeky mo...,Mr Bean - Chemistry experiment,video,0,1447,26498
13,Cooking Sunday lunch? Here's how not to do it!...,Mr Bean - Dinner for Two,video,19154,588,18491
14,Empty,Timeline Photos,photo,167980,3695,157505
15,Mr Bean shows you how to get that all importan...,www.youtube.com,video,12179,194,11824
16,Having sleeping troubles? Let Mr. Bean show yo...,www.youtube.com,video,11419,325,11007
17,Empty,Timeline Photos,photo,272955,6584,258111
18,Happy Mother's Day! Aren't you glad Mr. Bean'...,Mr. Bean - How to stop a baby from crying,video,48030,2395,45624
19,Brand New Friday Fun! \r\nWill Mr Bean get his...,Timeline Photos,photo,58541,1734,56140
20,Relive the very best of Mr. Bean's very worst ...,Mr. Bean - Embarrassing Moments Compilation,video,28539,1931,26821
21,It's International Dance Day! Mr Bean has got ...,Mr. Bean (NEW Series) - Dancing Bean,video,22619,516,22036
22,Caption this...,Timeline Photos,photo,299330,6443,287368
23,"Monday mornings, Mr. Bean style!\r\nhttps://ww...",Mr. Bean - Alarm Clock,video,34144,1878,32687
24,Happy Earth Day! Mr Bean is doing his bit to l...,Mr Bean (NEW series) - Litterbugs Clip,video,29631,794,28880
25,Empty,Timeline Photos,photo,305983,7561,296668
26,Empty,Timeline Photos,photo,133245,2286,128606
27,Mr. Bean demonstrates the correct etiquette wh...,Mr Bean - Restaurant Etiquette,video,25504,575,24409
28,Empty,Timeline Photos,photo,331512,19652,318173
29,Warning: Don't try this at home!\r\nhttps://ww...,Mr. Bean - Fixing Your Own Teeth,video,39186,2106,37247
30,Happy Golfer's Day! Fancy some golfing tips fr...,Mr Bean - Crazy Golf,video,11564,886,10951
31,Empty,Timeline Photos,photo,470129,18989,451036
32,Summer is coming and you know what that means…...,Mr. Bean (NEW series) - Ice Cream,video,18682,614,18154
33,"Mr. Bean tries, before he buys! \r\nhttps://ww...",Mr. Bean - Shopping for Towels,video,24096,1684,22888
34,Empty,Timeline Photos,photo,72606,1835,70388
35,Empty,Timeline Photos,photo,136609,2943,131976
36,What could it be…?\r\nhttps://www.youtube.com/...,Mr. Bean - Mystery creature,video,16370,526,15887
37,Mr. Bean's unusual way of changing his money.\...,Mr. Bean - Saxophone Player,video,17157,1194,16411
38,Did you find all 11 easter eggs? HAPPY EASTER!!,Timeline Photos,photo,94598,2390,92290
39,Teddy has hidden 11 easter eggs but Mr Bean ca...,Timeline Photos,photo,15312,939,14838
40,"When a simple ""excuse me"" won't do!\r\nhttps:/...",Mr. Bean - Elderly people on stairs,video,26237,1684,25079
41,Rowan Atkinson officially says he will never w...,Rowan Atkinson: I will never wave goodbye to M...,link,98365,2581,94349
42,It's International Day of Happiness today! Spr...,Mr. Bean's Happy Moments,video,232440,41910,212499
43,Mr Bean was ahead of his time with his dance m...,Mr. Bean - At the Disco,video,16863,6,15987
44,Empty,Timeline Photos,photo,144332,5744,141303
45,Empty,Timeline Photos,photo,282389,19375,266105
46,Happy Napping Day! Mr. Bean always makes time ...,Mr. Bean - Sneezing and Snoozing In Church,video,19254,1526,18370
47,Happy Friday!,Timeline Photos,photo,325558,11754,313017
48,Its Pack Your Lunch Day!!! Mr Bean has made hi...,Mr. Bean - Making A Sandwich,video,29120,3607,27500
49,A different twist on a classic sleeping method...,Mr. Bean - Counting Sheep.,video,19725,1489,18847
50,What score out of 10 would you award Mr Bean f...,Mr. Bean - High Dive,video,25261,1715,23946
51,Happy Friday!!,Timeline Photos,photo,285043,21857,274426
52,Mr Bean and Teddy learn a valuable lesson abou...,Mr. Bean (NEW series) - The Lift,video,18379,481,17896
53,"Mr. Bean is having fun at the Country Fete, no...",Mr Bean - Country fete games -- Volksfest Spiele,video,30285,2010,28857
54,Look at this AMAZING Mr. Bean made out of Lego...,"Even in LEGO, Mr. Bean travels in comfort | Th...",link,31377,1145,29372
55,Watch Mr Bean plan his great escape…\r\nhttps:...,Mr Bean - Prison Break,video,22559,688,21741