In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta
import time

In [66]:
data = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/marathon_results_2016.csv', index_col='Bib', usecols=['Bib','40K','Half','Pace','Age','M/F','Country','State','City'])

countries = data["Country"].unique()

myGroup = {}
dics = {3 : 431, 5 : 4351}
for country in countries:
    newDataFrame = data.where(data['Country'] == country).dropna()
    myGroup[country] = newDataFrame


myGroup["CAN"]

        Age M/F           City State Country     Half      40K     Pace
Bib
228    34.0   M         Guelph    ON     CAN  1:16:12  2:25:57  0:05:52
77     41.0   M         Quebec    QC     CAN  1:13:38  2:26:05  0:05:54
1155   31.0   M      Vancouver    BC     CAN  1:17:13  2:29:29  0:06:03
369    33.0   M  Charlottetown    PE     CAN  1:18:01  2:31:24  0:06:08
239    30.0   M        Toronto    ON     CAN  1:16:32  2:31:35  0:06:10
...     ...  ..            ...   ...     ...      ...      ...      ...
29976  33.0   M        Toronto    ON     CAN  2:37:15  5:32:04  0:13:23
29794  38.0   M          Maple    ON     CAN  2:37:15  5:32:04  0:13:23
16949  36.0   F       Victoria    BC     CAN  2:40:37  5:29:14  0:13:25
31944  66.0   M     Unionville    ON     CAN  2:46:56  5:35:54  0:13:30
30383  41.0   M      Kitchener    ON     CAN  2:44:18  5:33:25  0:13:31

[2134 rows x 8 columns]

In [85]:
df = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/marathon_results_2016.csv', index_col='Bib',
usecols=['Bib','40K','Half','Pace','Age','M/F','Country',
 'State','City'])

df = df[(df['40K'] != '-') & (df['Half'] != '-')]

df['40K'] = df['40K'].apply(pd.to_timedelta)
df['Half'] = df['Half'].apply(pd.to_timedelta)

df['TotalSeconds'] = df['40K'].apply(lambda x: timedelta.total_seconds
(x))
df['HalfSeconds'] = df['Half'].apply(lambda x: timedelta.total_seconds
(x))

cities = df["City"].unique()

groupsDict = {}

for city in cities:
    zmienna = df.where(df["City"] == city).dropna(how = 'all')
    groupsDict[city] = zmienna

groupsDict["Addis Ababa"]


#zmienna = df.where(df["City"] == "Addis Ababa").dropna(how='all')
#zmienna

,Age,M/F,City,State,Country,Half,40K,Pace,TotalSeconds,HalfSeconds
Bib,,,,,,,,,,
5,21.0,M,Addis Ababa,NaN,ETH,0 days 01:06:45,0 days 02:05:59,0:05:04,7559.0,4005.0
6,31.0,M,Addis Ababa,NaN,ETH,0 days 01:06:44,0 days 02:06:47,0:05:07,7607.0,4004.0
7,29.0,M,Addis Ababa,NaN,ETH,0 days 01:06:45,0 days 02:10:57,0:05:18,7857.0,4005.0
4,20.0,M,Addis Ababa,NaN,ETH,0 days 01:06:45,0 days 02:14:23,0:05:26,8063.0,4005.0
F14,24.0,F,Addis Ababa,NaN,ETH,0 days 01:15:32,0 days 02:30:52,0:06:06,9052.0,4532.0

In [ ]:
df = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/marathon_results_2016.csv', index_col='Bib',
usecols=['Bib','40K','Half','Pace','Age','M/F','Country',
 'State','City'])

df = df[(df['40K'] != '-') & (df['Half'] != '-')]

df['40K'] = df['40K'].apply(pd.to_timedelta)
df['Half'] = df['Half'].apply(pd.to_timedelta)

df['TotalSeconds'] = df['40K'].apply(lambda x: timedelta.total_seconds
(x))
df['HalfSeconds'] = df['Half'].apply(lambda x: timedelta.total_seconds
(x))

group_city = df.groupby("City")
group_city.get_group("San Francisco")["40K"].mean()

group_city.get_group("34-120 Andrychow")["40K"].mean()

group_city.first()

group_age = df.groupby("Age")
group_age.get_group(20)["40K"].mean()
group_age.get_group(40)["40K"].mean()

group_age.first()


group_age_mean = df.groupby("Age")["40K"].mean()
group_age_mean.loc[[20,40,30]]

Age
20   0 days 03:36:54.583333
40   0 days 03:35:22.724557
30   0 days 03:32:54.006472
Name: 40K, dtype: timedelta64[us]

In [2]:
df = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/marathon_results_2016.csv', index_col='Bib',
usecols=['Bib','40K','Half','Pace','Age','M/F','Country',
 'State','City'])

df = df[(df['40K'] != '-') & (df['Half'] != '-')]

df['40K'] = df['40K'].apply(pd.to_timedelta)
df['Half'] = df['Half'].apply(pd.to_timedelta)

df['TotalSeconds'] = df['40K'].apply(lambda x: timedelta.total_seconds
(x))
df['HalfSeconds'] = df['Half'].apply(lambda x: timedelta.total_seconds
(x))

group_city = df.groupby(by="City")
group_city.mean(numeric_only=True)

group_city["TotalSeconds"].sum().to_frame().sort_values(by="TotalSeconds")
len(group_city.get_group("New York"))
group_age = df.groupby(by="Age")
group_age["40K"].count().to_frame()

#aa = df.pivot_table(values = '40K', columns="Country", index="Age", aggfunc="mean").dropna(axis = 1, how = "all")
#aa
bb = df.groupby(["Age", "Country"])["40K"].mean().to_frame()
bb

country_city = df.groupby(["Country", "City"])
country_city.size()
country_city.mean(numeric_only=True)
country_city.get_group(("USA", "San Francisco"))

sex_age = df.groupby(["M/F","Age"])
ss = sex_age.size().to_frame()
dd = sex_age.mean(numeric_only=True)
ss.rename(columns= {0 : "count"},inplace=True)
ss.rename({"F" : "KOBIETY", "M" : "MĘŻCZYŹNI"},inplace=True)
dd.rename({"F" : "KOBIETY", "M" : "MĘŻCZYŹNI"},inplace=True)

połączone_poziomo = pd.concat([ss, dd], axis=1)
połączone_poziomo
pd.concat([ss,dd])
sex_age.get_group(("M",25))

,Age,M/F,City,State,Country,Half,40K,Pace,TotalSeconds,HalfSeconds
Bib,,,,,,,,,,
271,25,M,Hull,MA,USA,0 days 01:12:57,0 days 02:23:40,0:05:48,8620.0,4377.0
200,25,M,Colorado Springs,CO,USA,0 days 01:15:01,0 days 02:25:27,0:05:51,8727.0,4501.0
124,25,M,Auckland,NaN,NZL,0 days 01:12:31,0 days 02:24:55,0:05:53,8695.0,4351.0
452,25,M,Philadelphia,PA,USA,0 days 01:14:31,0 days 02:27:25,0:05:58,8845.0,4471.0
216,25,M,Chicago,IL,USA,0 days 01:17:30,0 days 02:29:15,0:06:01,8955.0,4650.0
...,...,...,...,...,...,...,...,...,...,...
30589,25,M,Watham,MA,USA,0 days 02:32:40,0 days 05:12:44,0:12:30,18764.0,9160.0
28626,25,M,Draper,UT,USA,0 days 02:28:46,0 days 05:19:13,0:12:54,19153.0,8926.0
30754,25,M,St. Louis,MO,USA,0 days 02:15:46,0 days 05:20:44,0:13:00,19244.0,8146.0
27001,25,M,Watertown,MA,USA,0 days 02:42:56,0 days 05:38:08,0:13:34,20288.0,9776.0
28889,25,M,Leominster,MA,USA,0 days 02:42:10,0 days 05:38:51,0:13:37,20331.0,9730.0

In [ ]:
df = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/marathon_results_2016.csv', index_col='Bib',
usecols=['Bib','40K','Half','Pace','Age','M/F','Country',
 'State','City'])

df = df[(df['40K'] != '-') & (df['Half'] != '-')]

df['40K'] = df['40K'].apply(pd.to_timedelta)
df['Half'] = df['Half'].apply(pd.to_timedelta)

df['TotalSeconds'] = df['40K'].apply(lambda x: timedelta.total_seconds
(x))
df['HalfSeconds'] = df['Half'].apply(lambda x: timedelta.total_seconds
(x))

sex_age = df.groupby(by=["M/F","Age"])


sex_age.agg({"HalfSeconds" : ["sum","mean", "max"], "TotalSeconds" : ["sum","mean", "max"]})

functions = ["sum","mean", "max"]

sex_age.agg({"HalfSeconds" : functions, "TotalSeconds" : functions})


countrygr = df.groupby(by="Country")
lista = {}

for country, countryData in countrygr:
    min = countryData.HalfSeconds.idxmin()
    bestRunner = df.loc[min]
    lista[country] = bestRunner


wynikdf = pd.DataFrame(lista).T

newDF = pd.DataFrame()
lista2 = {}
for country, countryData in countrygr:

    bestRN2 = countryData.loc[countryData.HalfSeconds.idxmin()]
    lista2[country] = bestRN2
    
wynikdf2 = pd.DataFrame(lista2).T
wynikdf2

Age                          33
M/F                           M
City                     Harare
State                       NaN
Country                     ZIM
Half            0 days 01:06:47
40K             0 days 02:11:48
Pace                    0:05:26
TotalSeconds             7908.0
HalfSeconds              4007.0
Name: 16, dtype: object

In [ ]:
df = pd.read_csv('/Users/MarcelMiłkowski/OneDrive - DIGITAL TPA/moje/course-files/course-files/marathon_results_2016.csv', index_col='Bib',
usecols=['Bib','40K','Half','Pace','Age','M/F','Country',
 'State','City'])

df = df[(df['40K'] != '-') & (df['Half'] != '-')]

df['40K'] = df['40K'].apply(pd.to_timedelta)
df['Half'] = df['Half'].apply(pd.to_timedelta)

df['TotalSeconds'] = df['40K'].apply(lambda x: timedelta.total_seconds
(x))
df['HalfSeconds'] = df['Half'].apply(lambda x: timedelta.total_seconds
(x))


group_city = df.groupby(by="City")

#for city in group_city:
 #   print(city[0], len(city[1]))

#for city, cityData in group_city:
#    print(city, cityData.loc[cityData["TotalSeconds"].idxmin()])

#for city, cityData in group_city:
 #   print(city, cityData.nsmallest(columns="TotalSeconds"))

the_best_per_city = pd.DataFrame()

for city, cityData in group_city:
    the_best_per_city = pd.concat([the_best_per_city, cityData.nsmallest(1,columns="TotalSeconds")])   

the_best_per_city

,Age,M/F,City,State,Country,Half,40K,Pace,TotalSeconds,HalfSeconds
Bib,,,,,,,,,,
6229,39,F,0851 Oslo,NaN,NOR,0 days 01:35:31,0 days 03:15:24,0:07:55,11724.0,5731.0
4186,35,M,20832,MD,USA,0 days 01:35:57,0 days 03:14:00,0:07:51,11640.0,5757.0
31786,44,F,34-120 Andrychow,NaN,POL,0 days 01:58:39,0 days 03:55:09,0:09:28,14109.0,7119.0
15350,58,M,5700 Svendborg,NaN,DEN,0 days 01:49:12,0 days 03:44:58,0:09:05,13498.0,6552.0
20668,46,F,95630,CA,USA,0 days 01:50:25,0 days 03:37:23,0:08:44,13043.0,6625.0
...,...,...,...,...,...,...,...,...,...,...
2978,42,M,Zurich,NaN,SUI,0 days 01:32:09,0 days 03:03:15,0:07:26,10995.0,5529.0
31756,58,F,Zweibruecken,NaN,GER,0 days 02:22:22,0 days 04:56:52,0:11:57,17812.0,8542.0
31280,61,M,Zwevegem,NaN,BEL,0 days 02:15:30,0 days 04:42:02,0:11:18,16922.0,8130.0
4052,46,M,Zwolle,NaN,NED,0 days 01:33:21,0 days 03:04:11,0:07:27,11051.0,5601.0
1507,32,M,hingham,MA,USA,0 days 01:24:38,0 days 02:45:08,0:06:39,9908.0,5078.0

In [ ]:
a = len(group_city)
a

5825