In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Imported")

Imported

In [25]:
products = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/products.csv")
categories = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/categories1.csv")
suppliers = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/suppliers.csv")
products[products["ProductName"] == "Ravioli Angelo"]
categories.loc[categories["CategoryID"] == 5]
suppliers.loc[suppliers["Country"] == "France"]
#uppliers.loc[27]

,SupplierID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,HomePage
17,18,Aux joyeux ecclésiastiques,Guylène Nodier,Sales Manager,203 Rue des Francs-Bourgeois,Paris,NaN,75004,France,(1) 03.83.00.68,(1) 03.83.00.62,NaN
26,27,Escargots Nouveaux,Marie Delamare,Sales Manager,22 rue H. Voiron,Montceau,NaN,71300,France,85.57.00.07,NaN,NaN
27,28,Gai pâturage,Eliane Noz,Sales Representative,Bat. B 3 rue des Alpes,Annecy,NaN,74000,France,38.76.98.06,38.76.98.58,NaN

In [14]:
mrbeanData = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/mrbean_facebook_statuses_join.csv", usecols=['status_message_mrbean','status_type','num_likes'])
nasaData = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/nasa_facebook_statuses_join.csv", usecols=['status_message_nasa','status_type','num_likes'])
nasaData
fb = pd.concat(objs= [mrbeanData,nasaData],sort=True,ignore_index=True)
fb.loc[fb.index == 0]

nasaData.rename({"status_message_nasa":"status_message"},inplace=True, axis=1)
mrbeanData.rename({"status_message_mrbean":"status_message"},inplace=True, axis=1)

fb2 = pd.concat(objs= [mrbeanData,nasaData],sort=True,ignore_index=True)
fb2

     num_likes                                     status_message status_type
0        16079  It's time for Mr Bean and Teddy to get ready f...       video
1       114008                                                NaN       photo
2       218579                                                NaN       photo
3        20338  Mr Bean is ready to do some shopping but bewar...       video
4       215591                                                NaN       photo
..         ...                                                ...         ...
814      39355  You've never seen Pluto like this before! New ...       photo
815      11835  Our cooperative field study in East Asia advan...       photo
816      15567  After spending a #YearInSpace, astronaut Scott...       photo
817      41584  Gravitational waves, predicted by Einstein and...       photo
818      12793  Have you ever used a GPS to help you get somew...       photo

[819 rows x 3 columns]

In [4]:
customer_names = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/customers.csv", usecols=['CustomerID',"CompanyName"])
customer_cities = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/customers.csv", usecols=['CustomerID',"City","Country"])
len(customer_cities)

customer_cities.set_index('CustomerID', inplace=True)
customer_names.set_index('CustomerID', inplace=True)
#customer_names.join(customer_cities)
#customer_cities.join(customer_names)
customer_names.reset_index(inplace=True)
customer_names.join(customer_cities, on="CustomerID")
#customer_cities.join(customer_names, on="CustomerID")

   CustomerID                         CompanyName          City  Country
0       ALFKI                 Alfreds Futterkiste        Berlin  Germany
1       ANATR  Ana Trujillo Emparedados y helados  M?©xico D.F.   Mexico
2       ANTON            Antonio Moreno Taquer?­a  M?©xico D.F.   Mexico
3       AROUT                     Around the Horn        London       UK
4       BERGS                 Berglunds snabbk?¶p        Lule??   Sweden
..        ...                                 ...           ...      ...
86      WARTH                      Wartian Herkku          Oulu  Finland
87      WELLI              Wellington Importadora       Resende   Brazil
88      WHITC                White Clover Markets       Seattle      USA
89      WILMK                         Wilman Kala      Helsinki  Finland
90      WOLZA                      Wolski  Zajazd      Warszawa   Poland

[91 rows x 4 columns]

In [2]:
f_2015=pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/Fortune_500_2015.csv", usecols=['rank','company'])
f_2016=pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/Fortune_500_2016.csv", usecols=['rank','company'])
f_2015
companies_2015_2016 = f_2015.merge(f_2016,on="company", suffixes=["_2015", "_2016"])
companies_2015_2016 =companies_2015_2016.reindex(columns=["rank_2015", "rank_2016","company"])
companies_2015_2016.loc[companies_2015_2016["company"] == "Microsoft"]

companies_2015_20162zadanie = f_2015.merge(f_2016,on="company", suffixes=["_2015", "_2016"],indicator=True, how="inner")
companies_2015_20162zadanie
#f_2016[f_2016["rank"] == "NaN"]
#f_2016[f_2016["company"] == "Pioneer Natural Resources"]
only_2015 = f_2015.merge(f_2016,on="company", suffixes=["_2015", "_2016"],indicator=True, how="left_anti")
only_2015
only_2016 = f_2015.merge(f_2016,on="company", suffixes=["_2015", "_2016"],indicator=True, how="right_anti")
only_2016

     rank_2015                       company  rank_2016      _merge
125        NaN                       Arconic        126  right_only
152        NaN                   Kraft Heinz        153  right_only
184        NaN        Performance Food Group        185  right_only
268        NaN         Hertz Global Holdings        269  right_only
306        NaN               PayPal Holdings        307  right_only
314        NaN                        Univar        315  right_only
322        NaN                       Veritiv        323  right_only
352        NaN                 XPO Logistics        353  right_only
396        NaN   Coca-Cola European Partners        397  right_only
419        NaN                       Baxalta        420  right_only
428        NaN          Constellation Brands        429  right_only
430        NaN        Zimmer Biomet Holdings        431  right_only
436        NaN              WEC Energy Group        437  right_only
446        NaN        Quintiles IMS Holdings        447  right_only
456        NaN            Genesis Healthcare        457  right_only
460        NaN       Frontier Communications        461  right_only
468        NaN  Envision Healthcare Holdings        469  right_only
470        NaN           Arthur J. Gallagher        471  right_only
475        NaN                        Markel        476  right_only
480        NaN                    S&P Global        481  right_only
481        NaN       Raymond James Financial        482  right_only
483        NaN                        Airgas        484  right_only
484        NaN                ABM Industries        485  right_only
485        NaN      Citizens Financial Group        486  right_only
487        NaN          Simon Property Group        488  right_only
489        NaN              Rockwell Collins        490  right_only
490        NaN                  Lam Research        491  right_only
491        NaN                        Fiserv        492  right_only
494        NaN                      Big Lots        495  right_only
495        NaN      Telephone & Data Systems        496  right_only
496        NaN      First American Financial        497  right_only
497        NaN                           NVR        498  right_only
498        NaN          Cincinnati Financial        499  right_only
499        NaN             Burlington Stores        500  right_only

In [ ]:
products = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/products_del_1.csv", usecols=["ProductID","ProductName","SupplierID"])
suppliers = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/suppliers_del_1.csv",usecols=["SupplierID", "CompanyName", "City"])

prod_and_sup = products.merge(right=suppliers,how="inner")

prod_and_sup_outer = products.merge(right=suppliers,how="outer", indicator=True)
prod_and_sup_outer.loc[prod_and_sup_outer["_merge"] != "both"]
prod_and_sup = products.merge(right=suppliers,how="o ")
prod_and_sup

,ProductID,ProductName,SupplierID,CompanyName,City
0,1.0,Chai,1,Exotic Liquids,London
1,2.0,Chang,1,Exotic Liquids,London
2,3.0,Aniseed Syrup,1,Exotic Liquids,London
3,4.0,Chef Anton's Cajun Seasoning,2,New Orleans Cajun Delights,New Orleans
4,5.0,Chef Anton's Gumbo Mix,2,New Orleans Cajun Delights,New Orleans
...,...,...,...,...,...
71,57.0,Ravioli Angelo,26,Pasta Buttini s.r.l.,Salerno
72,NaN,NaN,27,Escargots Nouveaux,Montceau
73,60.0,Camembert Pierrot,28,Gai pâturage,Annecy
74,61.0,Sirop d'érable,29,Forêts d'érables,Ste-Hyacinthe
75,62.0,Tarte au sucre,29,Forêts d'érables,Ste-Hyacinthe

In [25]:
products = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/products_del_1.csv", usecols=["ProductID","ProductName","SupplierID"])
suppliers = pd.read_csv("C:/Users/marce/OneDrive/Dokumenty/Analiza danych/py2/course-files/northwind-mongo-master/suppliers_del_1.csv",usecols=["SupplierID", "CompanyName", "City"])

prod_sup = products.merge(right=suppliers,on="SupplierID",how="outer", indicator=True)
filtr = prod_sup["_merge"] == "right_only"
prod_sup[filtr]
NewOrlean = prod_sup["CompanyName"] == "New Orleans Cajun Delights"
prod_sup[NewOrlean]

,ProductID,ProductName,SupplierID,CompanyName,City,_merge
3,4.0,Chef Anton's Cajun Seasoning,2,New Orleans Cajun Delights,New Orleans,both
4,5.0,Chef Anton's Gumbo Mix,2,New Orleans Cajun Delights,New Orleans,both
5,65.0,Louisiana Fiery Hot Pepper Sauce,2,New Orleans Cajun Delights,New Orleans,both
6,66.0,Louisiana Hot Spiced Okra,2,New Orleans Cajun Delights,New Orleans,both